name: converter
version: 0.7.6
description: A package for encoding/decoding DICOM binary, json, ...
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/convert

environment:
  sdk: '>=2.0.0 < 3.0.0'

dependencies:
  core:
    path: ../core
    version: ^0.7.6
  xml: any

dev_dependencies:
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  io_extended:
    path: ../io_extended
    version: ^0.7.5
  path: ^1.6.2
  test: any
  test_tools:
    path: ../../test_tools
    version: ^0.7.5



