# TODO: figure out why "convert" doesn't work for name.
name: dcm_convert
version: 0.6.0
description: A package for encoding/decoding DICOM binary, json, ...
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/convert

environment:
  sdk: ^1.24.2

dependencies:
  core:
    path: C:/odw/sdk/core
    version: ^0.6.1
  logger:
    path: C:/odw/sdk/logger
    version: ^0.6.1
  subject:
    path: C:/odw/sdk/subject
    version: ^0.6.1
  system:
    path: C:/odw/sdk/system
    version: ^0.6.1
  tag:
    path: C:/odw/sdk/tag
    version: ^0.6.1
  uid:
    path: C:/odw/sdk/uid
    version: ^0.6.1


dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test:  ^0.12.0


