# TODO: figure out why "convert" doesn't work for name.
name: convert
version: 0.7.2
description: A package for encoding/decoding DICOM binary, json, ...
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/convert

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  args: any
  core:
    path: C:/odw/sdk/core
    version: ^0.7.2
  io:
    path: C:/odw/sdk/io
    version: ^0.7.0

dev_dependencies:
  benchmark_harness: any
  grinder: ^0.8.0+2
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.0



