name: convertX
version: 0.5.0
description: A package for encoding/decoding DICOM binary, json, ...
author: Jim Philbin <jfphilbin@gmail.com>
homepage: https://github.com/OpenDICOMweb/convert

environment:
  sdk: ^1.0.0

dependencies:
  common:
    path: C:/odw/sdk/common
    version: ^0.5.2
  dictionary:
    path: C:/odw/sdk/dictionary
    version: ^0.5.1
  core:
    path: C:/odw/sdk/core
    version: ^0.5.1

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test:  ^0.12.0


